# Generated by Django 6.0.6 on 2026-06-06 09:08

import django.db.models.deletion
import ophix_creds.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ophix_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('secret_json', ophix_creds.fields.EncryptedJSONField(default=dict, verbose_name='secret JSON')),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Credential',
                'verbose_name_plural': 'Credentials',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ClientCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Client can read this artifact (can_read).', verbose_name='enabled')),
                ('can_update', models.BooleanField(default=False, help_text='Client may overwrite this artifact.', verbose_name='can update')),
                ('can_delete', models.BooleanField(default=False, help_text='Client may delete this artifact.', verbose_name='can delete')),
                ('can_share', models.BooleanField(default=False, help_text='Reserved: future client-driven sharing. Currently unused.', verbose_name='can share')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ophix_core.client', verbose_name='client')),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_links', to='ophix_creds.credential', verbose_name='credential')),
            ],
            options={
                'verbose_name': 'Client Credential',
                'verbose_name_plural': 'Client Credentials',
                'unique_together': {('client', 'credential')},
            },
        ),
    ]
