# Generated by Django 5.2.12 on 2026-05-01 10:44

import django.db.models.deletion
import ophix_creds.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ophix_core', '0003_alter_accesslog_options_alter_client_options_and_more'),
        ('ophix_creds', '0002_encrypt_secret_json'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientcredential',
            options={'verbose_name': 'Client Credential', 'verbose_name_plural': 'Client Credentials'},
        ),
        migrations.AlterModelOptions(
            name='credential',
            options={'ordering': ('name',), 'verbose_name': 'Credential', 'verbose_name_plural': 'Credentials'},
        ),
        migrations.AlterField(
            model_name='clientcredential',
            name='can_delete',
            field=models.BooleanField(default=False, help_text='Client may delete this artifact.', verbose_name='can delete'),
        ),
        migrations.AlterField(
            model_name='clientcredential',
            name='can_share',
            field=models.BooleanField(default=False, help_text='Reserved: future client-driven sharing. Currently unused.', verbose_name='can share'),
        ),
        migrations.AlterField(
            model_name='clientcredential',
            name='can_update',
            field=models.BooleanField(default=False, help_text='Client may overwrite this artifact.', verbose_name='can update'),
        ),
        migrations.AlterField(
            model_name='clientcredential',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ophix_core.client', verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='clientcredential',
            name='credential',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_links', to='ophix_creds.credential', verbose_name='credential'),
        ),
        migrations.AlterField(
            model_name='clientcredential',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Client can read this artifact (can_read).', verbose_name='enabled'),
        ),
        migrations.AlterField(
            model_name='clientcredential',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='enabled'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='secret_json',
            field=ophix_creds.fields.EncryptedJSONField(default=dict, verbose_name='secret JSON'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
    ]
